### ISSUE TITLE
Desktop environment issues?

### ISSUE THREAD

**Issue by Usulyre** [MilkyDeveloper/Campfire2#2]
I couldn't get any desktop environment to show up on the blank windows when using "DISPLAY=:0 Xephyr -resizeable -fullscreen :1; export DISPLAY=:1"

I tried this and it works to show desktop, but is this ok? Xephyr -ac -resizeable -fullscreen -terminate -reset :1 & DISPLAY=:1"

Also I can't seem to find a way to quit the blank window? If I force close it, cmdline says it still is running and I have to restart chrome os to get it close completely, any way to completely close without having to resort to system restart?

How does one access local files, meaning my chrome os files or a usb drive or sd card from the desktop environment? It doesn't have any directories that seem to point to any local files or usb drives like crouton.

Also, i tried cinnamon desktop and it reports that it has to run in software rendering mode increasing cpu usage, how do I prevent this. I typed in the cmd echo -e "# Fix 3d Acceleration on Kernel 4.4\nexport MESA_LOADER_DRIVER_OVERRIDE=i965" >> ~/.bashrc && source ~/.bashrc" but it doesn't work with cinnamon desktop, but single apps work.

Does sound work in the desktop environment?

**Comment by MilkyDeveloper** [comment]
Sorry for the very late reply. I was working on something that let's you run Ubuntu natively. Anyways, you can use `Xephyr -ac -resizeable -fullscreen -terminate -reset :1 & export DISPLAY=:1`. If you want to quit the blank window, you can do `killall Xephyr`.

Accessing local files is pretty easy. Just do something like:
```
sudo mkdir /usr/local/ubuntu/directory
sudo mount --bind ~/Downloads /usr/local/ubuntu/directory
```
and then voila, your Downloads folder of ChromeOS is in your chroot.

If you want GPU Acceleration everywhere, put this in `/root/.drirc` (in your chroot):
```
<driconf>
  <device driver="loader" kernel_driver="i915">
    <option name="dri_driver" value="i965" />
  </device>
</driconf>
```

Sound is complicated. ALSA works, but PulseAudio doesn't. Therefore, if you want anything with sound, open the terminal and type `apulse` before it. It's pretty shoddy, but soon I'll be releasing the updated version of this project which fixes a **lot** of bugs.
